### ISSUE TITLE
Improve tests for more confidence in introducing changes

### ISSUE THREAD

**Issue by hanapedia** [hanapedia/hexagon#82]
## Why
Would like to imporove tests so that we can introduce bigger changes with more confidence. 
Currently, only integration test for major functions are present.

## Goal
Standardizes unit tests and integration tests.
Ideally, integrate the tests into developement workflow.

## Work plan
0. Along the way, always try to add doc comments where needed
1. Implement Unit tests on major functionalities
  - Service unit intialization
    - [x] is the config file read properly?
    - [x] is the config file content validated properly?
    - [x] are primary adapters setup with proper configuration?
    - [x] are secondary adapters setup with proper configuration?
    - [x] are secondary adapters mapped to primary adatpers correctly?
  - hexctl commands
    - [ ] `generate`: Are Kubernetes manifests generated correctly?
    - [ ] `validate`: Are config files validated correctly?
    - [ ] `graph`: Does it produce correct graphs?
2. Implement Integration tests for runtime check
  - Service unit executes
    - [ ] test the primary adapter and secondary adapter of each kind at the same time by invoking the primary adapter with corresponding secondary adapter
    - [x] #83
