### ISSUE TITLE
version 1.1.0 checklist

### ISSUE THREAD

**Issue by hanapedia** [hanapedia/hexagon#85]
## Version summary
This version will include the following improvements and features.
- [x] QoL changes
  - [x] CI pipeline
  - [x] improved unit and integration tests
  - [x] Documentation
- [x] #102
  - [x] retries
  - [x] timeout
  - [x] error handling execution path
- [ ] New primary and secondary adapters
  - [ ] startup primary adapter
  - [ ] batch primary adapter
- [ ] improved schema validations
